function psi = Real_time_evolve_sphere_single_component( ...
    psi, ...
    m_a, ...
    g_a, ...
    N_a, ...
    L_z, ...
    Mat_V, ...
    geom, hbar, dt, l_filter)

% REAL_TIME_EVOLVE_SPHERE_SINGLE_COMPONENT
% One RK4 step of the single-component real-time GPE on a sphere,
% followed by renormalization.
%
% INPUTS
%   psi      : wavefunction
%   m_a      : mass
%   g_a      : intra-species 3D coupling
%   N_a      : atom number
%   L_z      : effective radial thickness used for 3D -> 2D reduction
%   Mat_V    : external potential
%   geom     : spherical geometry struct
%   hbar     : reduced Planck constant
%   dt       : real-time step
%   l_filter : spectral filter cutoff (optional, default = 18)
%
% OUTPUT
%   psi      : updated normalized wavefunction

    if nargin < 10 || isempty(l_filter)
        l_filter = 18;
    end

    Hpsi = Real_time_iteration_sphere_single_component( ...
        psi, ...
        m_a, ...
        g_a, ...
        N_a, ...
        L_z, ...
        Mat_V, ...
        geom, hbar);

    k_1 = -1i * dt / hbar * Hpsi;

    Hpsi = Real_time_iteration_sphere_single_component( ...
        psi + k_1/2, ...
        m_a, ...
        g_a, ...
        N_a, ...
        L_z, ...
        Mat_V, ...
        geom, hbar);

    k_2 = -1i * dt / hbar * Hpsi;

    Hpsi = Real_time_iteration_sphere_single_component( ...
        psi + k_2/2, ...
        m_a, ...
        g_a, ...
        N_a, ...
        L_z, ...
        Mat_V, ...
        geom, hbar);

    k_3 = -1i * dt / hbar * Hpsi;

    Hpsi = Real_time_iteration_sphere_single_component( ...
        psi + k_3, ...
        m_a, ...
        g_a, ...
        N_a, ...
        L_z, ...
        Mat_V, ...
        geom, hbar);

    k_4 = -1i * dt / hbar * Hpsi;

    psi = psi + (k_1 + 2*k_2 + 2*k_3 + k_4)/6;

    % Optional weak spectral filtering if needed
    psi = Spectral_filter_sphere(psi, geom, l_filter);

    % Renormalize
    psi = sphere_normalize(psi, geom.W);

end