function [psi, Hpsi] = Imaginary_time_evolve_sphere_single_component( ...
    psi, ...
    m_a, ...
    g_a, ...
    N_a, ...
    L_z, ...
    Mat_V, ...
    geom, hbar, dt)

%IMAGINARY_TIME_EVOLVE_SPHERE_SINGLE_COMPONENT Perform one imaginary-time step.
%
% INPUTS
%   psi   - wavefunction normalized on the spherical grid
%   m_a   - atomic mass
%   g_a   - three-dimensional intra-species coupling
%   N_a   - atom number
%   L_z   - effective transverse thickness
%   Mat_V - external potential on the sphere
%   geom  - spherical-grid geometry structure
%   hbar  - reduced Planck constant
%   dt    - imaginary-time step
%
% OUTPUTS
%   psi   - updated and normalized wavefunction
%   Hpsi  - Hamiltonian applied to the updated wavefunction

    % Hamiltonian action on current state
    Hpsi = Imaginary_time_iteration_sphere_single_component( ...
        psi, ...
        m_a, ...
        g_a, ...
        N_a, ...
        L_z, ...
        Mat_V, ...
        geom, hbar);

    % Forward Euler step in imaginary time
    k_1 = -dt / hbar * Hpsi;
    psi = psi + k_1;

    % Spectral filtering to suppress high-l noise
    psi = Spectral_filter_sphere(psi, geom, 18);

    % Renormalization on the sphere
    psi = sphere_normalize(psi, geom.W);

    % Recompute Hpsi on updated normalized state
    Hpsi = Imaginary_time_iteration_sphere_single_component( ...
        psi, ...
        m_a, ...
        g_a, ...
        N_a, ...
        L_z, ...
        Mat_V, ...
        geom, hbar);

end